apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: so-rest
  namespace: dots
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - path: /docs
        pathType: Exact
        backend:
          service: 
            name: so-rest
            port: 
              number: 8001
      - path: /openapi.json
        pathType: Exact
        backend:
          service: 
            name: so-rest
            port: 
              number: 8001
      - path: /api/v1/simulation
        pathType: Prefix
        backend:
          service: 
            name: so-rest
            port: 
              number: 8001
